// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Lock$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Lock";
  readonly sourceName: "contracts/Lock.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"_unlockTime","type":"uint256"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"unlockTime","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x608060405234801561000f575f80fd5b506040516100d13803806100d183398101604081905261002e91610035565b5f5561004c565b5f60208284031215610045575f80fd5b5051919050565b6079806100585f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c8063251c1aa314602a575b5f80fd5b60315f5481565b60405190815260200160405180910390f3fea26469706673582212200a4d162f764d325e6c2771f6e216fc5eef64a0cd7e16afeb434a2162e145904064736f6c63430008150033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b50600436106026575f3560e01c8063251c1aa314602a575b5f80fd5b60315f5481565b60405190815260200160405180910390f3fea26469706673582212200a4d162f764d325e6c2771f6e216fc5eef64a0cd7e16afeb434a2162e145904064736f6c63430008150033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Lock.sol";
  readonly buildInfoId: "solc-0_8_21-cb8961c895d5f4bf60baf56f2b9fbd22e5f01dd9";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Lock"]: Lock$Type;
    ["contracts/Lock.sol:Lock"]: Lock$Type;
  }
}